import type { Handle } from '@sveltejs/kit';

// Content-Security-Policy is generated by SvelteKit's kit.csp config (see svelte.config.js)
// so it can attach the nonce/hash its own inline hydration script needs.
export const SECURITY_HEADERS = {
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'no-referrer',
  'X-Content-Type-Options': 'nosniff',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()'
} as const;

export const handle: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
    response.headers.set(key, value);
  }
  return response;
};
