#!/usr/bin/env sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
test_digest=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
test_image="ghcr.io/registrystack/solmara-test@sha256:$test_digest"

check_compose() {
  REGISTRY_STACK_RELEASE_RELAY_DIGEST="$test_digest" \
  SOLMARA_EVIDENCE_IMAGE="$test_image" \
  SOLMARA_MINT_IMAGE="$test_image" \
  SOLMARA_STATIC_METADATA_IMAGE="$test_image" \
  SOLMARA_SCENARIO_RUNNER_IMAGE="$test_image" \
  SOLMARA_AUTHORITY_PROVISIONER_IMAGE="$test_image" \
  SOLMARA_TRANSIT_SIGNER_IMAGE="$test_image" \
  SOLMARA_HOME_IMAGE="$test_image" \
  SOLMARA_PORTAL_IMAGE="$test_image" \
  SOLMARA_ESIGNET_RELAY_IMAGE="$test_image" \
  SOLMARA_ESIGNET_SEED_IMAGE="$test_image" \
  SOLMARA_ESIGNET_POSTGRES_IMAGE="$test_image" \
  SOLMARA_ESIGNET_UI_IMAGE="$test_image" \
  ESIGNET_REDIS_IMAGE="redis@sha256:b99ffd0554dc8d300230b9d1b9f2a129a6abf595bf8589883beb980ed1feae3d" \
  SOLMARA_ESIGNET_POSTGRES_PASSWORD=test \
  ESIGNET_DEMO_OTP=111111 \
  REGISTRY_ESIGNET_KYC_TOKEN_SECRET=test \
  REGISTRY_ESIGNET_PSUT_SECRET=test \
  REGISTRY_ESIGNET_KYC_KEYSTORE_PASSWORD=test \
  PORTAL_ESIGNET_CLIENT_PRIVATE_KEY_B64=test \
  NIA_ESIGNET_CLIENT_PRIVATE_JWK='{"kty":"RSA"}' \
  SOLMARA_DEMO_CLIENT_PRIVATE_JWK='{"kty":"EC"}' \
  CHILD_BENEFIT_FEDERATOR_TOKEN=test \
  CRA_RELAY_AUDIT_KEY=test NIA_RELAY_AUDIT_KEY=test MOSD_RELAY_AUDIT_KEY=test \
  SIPF_RELAY_AUDIT_KEY=test SIPF_RELAY_CURSOR_KEY=test \
  NAGDI_RELAY_AUDIT_KEY=test NAGDI_RELAY_CURSOR_KEY=test \
  MINT_SIGNING_JWK=test MINT_SIGNING_PUBLIC_JWK=test MINT_AUDIT_HMAC_KEY=test \
  CRA_EVIDENCE_SIGNING_JWK=test CRA_EVIDENCE_SIGNING_PUBLIC_JWK=test CRA_EVIDENCE_AUDIT_HMAC_KEY=test CRA_EVIDENCE_SUBJECT_BINDING_HMAC_KEY=test \
  NIA_EVIDENCE_SIGNING_JWK=test NIA_EVIDENCE_SIGNING_PUBLIC_JWK=test NIA_EVIDENCE_AUDIT_HMAC_KEY=test NIA_EVIDENCE_SUBJECT_BINDING_HMAC_KEY=test \
  SRO_EVIDENCE_SIGNING_JWK=test SRO_EVIDENCE_SIGNING_PUBLIC_JWK=test SRO_EVIDENCE_AUDIT_HMAC_KEY=test SRO_EVIDENCE_SUBJECT_BINDING_HMAC_KEY=test \
  MOSD_EVIDENCE_SIGNING_JWK=test MOSD_EVIDENCE_SIGNING_PUBLIC_JWK=test MOSD_EVIDENCE_AUDIT_HMAC_KEY=test MOSD_EVIDENCE_SUBJECT_BINDING_HMAC_KEY=test \
  SIPF_EVIDENCE_SIGNING_JWK=test SIPF_EVIDENCE_SIGNING_PUBLIC_JWK=test SIPF_EVIDENCE_AUDIT_HMAC_KEY=test SIPF_EVIDENCE_SUBJECT_BINDING_HMAC_KEY=test \
  NAGDI_EVIDENCE_SIGNING_JWK=test NAGDI_EVIDENCE_SIGNING_PUBLIC_JWK=test NAGDI_EVIDENCE_AUDIT_HMAC_KEY=test NAGDI_EVIDENCE_SUBJECT_BINDING_HMAC_KEY=test \
  CRA_PENSION_EVIDENCE_CLIENT_PRIVATE_JWK=test CRA_CITIZEN_EVIDENCE_CLIENT_PRIVATE_JWK=test \
  MOSD_CHILD_BENEFIT_EVIDENCE_CLIENT_PRIVATE_JWK=test \
  SIPF_PENSION_EVIDENCE_CLIENT_PRIVATE_JWK=test SIPF_SURVIVOR_EVIDENCE_CLIENT_PRIVATE_JWK=test \
  NAGDI_VOUCHER_EVIDENCE_CLIENT_PRIVATE_JWK=test NAGDI_LIVESTOCK_EVIDENCE_CLIENT_PRIVATE_JWK=test \
  CRA_PENSION_EVIDENCE_CLIENT_PUBLIC_JWK=test CRA_CITIZEN_EVIDENCE_CLIENT_PUBLIC_JWK=test \
  MOSD_CHILD_BENEFIT_EVIDENCE_CLIENT_PUBLIC_JWK=test \
  SIPF_PENSION_EVIDENCE_CLIENT_PUBLIC_JWK=test SIPF_SURVIVOR_EVIDENCE_CLIENT_PUBLIC_JWK=test \
  NAGDI_VOUCHER_EVIDENCE_CLIENT_PUBLIC_JWK=test NAGDI_LIVESTOCK_EVIDENCE_CLIENT_PUBLIC_JWK=test \
  NIA_ESIGNET_CLIENT_PUBLIC_JWK=test SOLMARA_DEMO_CLIENT_PUBLIC_JWK=test \
  docker compose "$@" config >/dev/null
}

for compose in "$root"/compose.coolify*.yaml; do
  if [ "$(basename "$compose")" = "compose.coolify.esignet.yaml" ]; then
    continue
  fi
  check_compose -f "$compose"
done

# eSignet is intentionally an overlay: validate that it augments the same
# Portal service rather than accidentally declaring a second Portal deployment.
check_compose -f "$root/compose.coolify.yaml" -f "$root/compose.coolify.esignet.yaml"
