ARG REGISTRY_NOTARY_IMAGE=ghcr.io/registrystack/registry-notary@sha256:0cf05184885d7ed17dd9889e20f3797eb2a9ad07517f4ac7c05c03b774a00b8f
FROM ${REGISTRY_NOTARY_IMAGE}

COPY hosted/notaries /etc/registry-notary
